version: '3.8'

services:
  ngrok:
    image: ngrok/ngrok:alpine
    environment:
      NGROK_AUTHTOKEN: 1o4Jv6F9LpJVyc4XthPQwTRXILn_4gdTNK85sBzeVLShQBrQw
    command: 'http host.docker.internal:3000'
    ports:
      - '4040:4040'
    expose:
      - '4040'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4040/api/tunnels || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend
    image: backend-app
    working_dir: /app
    depends_on:
      - ngrok
    volumes:
      - ./backend:/app
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
    command: yarn start

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000

volumes:
  frontend-data:
  backend: